#!/bin/bash
NOW=`date +"%Y-%m-%d-%H-%M-%S"`
URL="ftp://ftp.sec.gov/edgar/full-index"
COMMAND="wget --background --output-file=wget-${NOW}.log --random-wait --no-host-directories --cut-dirs=2 --directory-prefix=ripd --recursive --accept company.Z --no-span-hosts --no-parent $URL"
echo $COMMAND
$COMMAND

