ALTER TABLE `taks_rawk`.`campuses` MODIFY COLUMN `year` SMALLINT(4) NOT NULL,
  MODIFY COLUMN `id` INTEGER UNSIGNED ZEROFILL NOT NULL,
  MODIFY COLUMN `district` MEDIUMINT(6) UNSIGNED ZEROFILL,
  MODIFY COLUMN `county` SMALLINT(3) UNSIGNED ZEROFILL DEFAULT NULL,
  MODIFY COLUMN `region` TINYINT(2) UNSIGNED ZEROFILL DEFAULT NULL,
  MODIFY COLUMN `closed` TINYINT(1) DEFAULT NULL,
  MODIFY COLUMN `enrollment` SMALLINT(5) DEFAULT NULL,
  MODIFY COLUMN `native` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `asian` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `black` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `hispanic` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `white` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `min_grade` TINYINT(3) DEFAULT NULL,
  MODIFY COLUMN `max_grade` TINYINT(3) DEFAULT NULL
  ;

ALTER TABLE `taks_rawk`.`student_campus_year` MODIFY COLUMN `year` SMALLINT(4) NOT NULL,
  MODIFY COLUMN `student_id` MEDIUMINT(8) UNSIGNED ZEROFILL NOT NULL,
  MODIFY COLUMN `campus_id` INTEGER UNSIGNED ZEROFILL NOT NULL,
  MODIFY COLUMN `district` MEDIUMINT(6) UNSIGNED ZEROFILL DEFAULT NULL,
  MODIFY COLUMN `county` SMALLINT(3) ZEROFILL UNSIGNED DEFAULT NULL,
  MODIFY COLUMN `region` TINYINT(2) UNSIGNED ZEROFILL DEFAULT NULL,
  MODIFY COLUMN `closed` TINYINT(1) DEFAULT NULL,
  MODIFY COLUMN `enrollment` SMALLINT(5) DEFAULT NULL,
  MODIFY COLUMN `native` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `asian` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `black` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `hispanic` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `white` FLOAT(3,3) DEFAULT NULL,
  MODIFY COLUMN `min_grade` TINYINT(3) DEFAULT NULL,
  MODIFY COLUMN `max_grade` TINYINT(3) DEFAULT NULL
  ; 

ALTER TABLE `taks_rawk`.`years`
  MODIFY COLUMN  y1		SMALLINT(4) 	NOT NULL,
  MODIFY COLUMN  y2		SMALLINT(4)
  ;

ALTER TABLE `taks_rawk`.`students`
  MODIFY COLUMN `year`  	SMALLINT(4) 	SIGNED   	  NOT NULL	COMMENT '',
  MODIFY COLUMN `id` 		MEDIUMINT 	UNSIGNED ZEROFILL NOT NULL	COMMENT '',
  MODIFY COLUMN `campus_id` 	INT  		UNSIGNED ZEROFILL DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `grade` 	TINYINT(2) 	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `missing` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'existed in prev. year, not anymore',
  MODIFY COLUMN `m_bin` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'binned raw;    NULL, 0, 1, .. 9',
  MODIFY COLUMN `m_irsp` 	TINYINT(2) 		 	  DEFAULT NULL	COMMENT 'corrected raw; NULL, 0..60, -1', 
  MODIFY COLUMN `m_raw` 	SMALLINT(5) 	SIGNED   	  DEFAULT NULL	COMMENT 'raw score;     NULL, 0..60    ', 
  MODIFY COLUMN `m_ssc` 	SMALLINT(5) 	SIGNED   	  DEFAULT NULL	COMMENT 'scaled score', 
  MODIFY COLUMN `m_met` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'met standards  NULL, 0, 1', 
  MODIFY COLUMN `m_com` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'commended      NULL, 0, 1', 
  MODIFY COLUMN `m_scode` 	CHAR(1) 		 	  DEFAULT NULL	COMMENT 'status code',
  MODIFY COLUMN `r_bin` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'binned raw;    NULL, 0, 1, .. 9',
  MODIFY COLUMN `r_irsp` 	TINYINT(2) 	 	 	  DEFAULT NULL	COMMENT 'corrected raw; NULL, 0..60, -1', 
  MODIFY COLUMN `r_raw` 	SMALLINT(5) 	SIGNED   	  DEFAULT NULL	COMMENT 'raw score;     NULL, 0..60    ', 
  MODIFY COLUMN `r_ssc` 	SMALLINT(5) 	SIGNED   	  DEFAULT NULL	COMMENT 'scaled score', 		  
  MODIFY COLUMN `r_met` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'met standards  NULL, 0, 1', 	  
  MODIFY COLUMN `r_com` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'commended      NULL, 0, 1', 	  
  MODIFY COLUMN `ethnic` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'Ethnicity;     NULL, 0, 1, .. 5',
  MODIFY COLUMN `disadv` 	TINYINT(1)	SIGNED   	  DEFAULT NULL	COMMENT 'Disadvantaged',
  MODIFY COLUMN `migsta` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'Migrant status',
  MODIFY COLUMN `titlei` 	TINYINT(1) 	SIGNED   	  DEFAULT NULL	COMMENT 'Title I status',
  MODIFY COLUMN `month` 	TINYINT(2) 	SIGNED   	  DEFAULT NULL	COMMENT 'Month of test'
  ;   
   

ALTER TABLE `taks_rawk`.`campuses`
  MODIFY COLUMN `year` 	SMALLINT(4) 	   	  NOT NULL,
  MODIFY COLUMN `id`		INT     	UNSIGNED ZEROFILL NOT NULL,
  MODIFY COLUMN `district` 	MEDIUMINT(6) 	UNSIGNED ZEROFILL DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `county` 	SMALLINT(3) 	UNSIGNED ZEROFILL DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `region` 	TINYINT(2) 	UNSIGNED ZEROFILL DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `closed` 	TINYINT(1)	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `enrollment` 	SMALLINT(5) 	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `native` 	FLOAT(3,3) 	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `asian` 	FLOAT(3,3) 	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `black` 	FLOAT(3,3) 	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `hispanic` 	FLOAT(3,3) 	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `white` 	FLOAT(3,3) 	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `min_grade` 	TINYINT(3) 	SIGNED   	  DEFAULT NULL	COMMENT '',
  MODIFY COLUMN `max_grade` 	TINYINT(3) 	SIGNED   	  DEFAULT NULL	COMMENT ''
  ; 
