#!/usr/bin/env bash

#
# Allows for parsing of any of the three possible raw twitter data
# heaps we have. Feel free to pass in a glob, just remember to escape
# it properly.
#
whichapi=$1   ; shift # the type of twitter data heap to parse {api|stream|search}
parse_time=$1 ; shift # the date to parse, ie. 201005\* or 20091202
hdfsdir=$1    ; shift # ouput location on hdfs

# s3 path to input data
s3bucket=s3n://monkeyshines.infochimps.org/data/ripd/com.tw

here=`dirname "$0"`

if [ "$whichapi" == "" ] ; then echo -e "\nUsage: $0 parse_type date_to_parse\n\n\texample: $0 api 20100502 /data/sn/tw/rawd/parsed\n" ; exit ; fi 
if [ "$whichapi" != "api" ] ; then
  input=${s3bucket}/com.twitter.${whichapi}/${parse_time}
else
  input=${s3bucket}/com.twitter/${parse_time}
fi

pattern="\*" # to remove glob if there is one
output=${hdfsdir}/${whichapi}/${parse_time%$pattern}

# Would like to be able to turn this off/on via arg
#
# echo "getting input size..."
# exec hdp-du ${input} 1>/dev/null
#
echo parse_twitter_${whichapi}_requests.rb --rm --run ${input} ${output} "$@"
exec ruby $here/parse_twitter_${whichapi}_requests.rb --rm --run ${input} ${output} "$@"
