#!/usr/bin/env bash

# input like this:
#
# a_follows_b 12345 66668
# a_follows_b 12345 66668
# a_follows_b 12345 66668
# a_follows_b 12345 66668
# a_follows_b 12222 99955
#
# becomes:
#
# a_follows_b 12345 66668
# a_follows_b 12222 99955
#
# note that we use 3 sort fields and 2 partition fields
#

input=${1}  ; shift
output=${1} ; shift
exec hdp-stream ${input} ${output} `which cat` `which uniq` 3 2
